version = 0.1
[default.deploy.parameters]
stack_name = "spotify-alerts-service"
resolve_s3 = true
s3_prefix = "spotify-alerts-service"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
