AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: blank

Resources:
  spotifyAlertsHandler:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs18.x
      Architectures: 
        - arm64
      Handler: index.handler
      CodeUri: src/handler
      MemorySize: 512
      Timeout: 10
      Environment:
        Variables:
          SPOTIFY_SECRETS_NAME: spotify-alerts-service-secrets
          LOG_LEVEL: DEBUG
          DYNAMO_DB_TABLE: !Ref spotifyAlertsTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "ES2020"
        Sourcemap: true
        EntryPoints:
          - index.ts
  
  spotifyAlertsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
